"""Initial Commit

Revision ID: 2767e6aff85e
Revises: None
Create Date: 2014-11-10 22:19:36.538169

"""

# revision identifiers, used by Alembic.
revision = '2767e6aff85e'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
